In [497]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [498]:
dataset = pd.read_csv('C:/Users/STAFF/Downloads/train.csv/train.csv')


In [499]:
data = pd.DataFrame(dataset)

In [500]:
data = data.dropna()

In [501]:
data.head(10)

Age    Occupation  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
6    23     Scientist      19114.12          1824.843333                2   
9    28       Teacher      34847.84          3037.986667                1   
12   28       Teacher      34847.84          3037.986667                1   
13   28       Teacher      34847.84          3037.986667                2   
15   28       Teacher      34847.84          3037.986667                2   
17   34      Engineer     143162.64         12187.220000                3   
21   34      Engineer     143162.64         12187.220000                2   
22   34      Engineer     143162.64         12187.220000                3   
23   34      Engineer     143162.64         12187.220000                2   
24   54  Entrepreneur      30689.89          2612.490833                2   

    NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
6               1             3          4                 3   
9               1             6          1                 7   
12              1             6          1                 3   
13              1             6          1                 3   
15              1             6          1                 3   
17              1             8          3                13   
21              1             8        967                 8   
22              1             8          3                 8   
23              1             8          3                 8   
24              1             4          1                 0   

    NumofDelayedPayment  ChangedCreditLimit  NumCreditInquiries CreditMix  \
6                   8.0               11.27                 4.0      Good   
9                   1.0                7.42                 2.0      Good   
12                  1.0                6.42                 2.0      Good   
13                  0.0                5.42                 2.0      Good   
15                  4.0                5.42                 2.0      Good   
17                  6.0                7.10                 3.0      Good   
21                  6.0                7.10                 3.0      Good   
22                  6.0                7.10                 3.0      Good   
23                  6.0                7.10                 3.0      Good   
24                  6.0                1.99                 4.0      Good   

    OutstandingDebt  CreditUtilizationRatio  CreditHitoryAge  \
6            809.98               22.537593            22.70   
9            605.03               38.550848            26.80   
12           605.03               34.977895            26.11   
13           605.03               33.381010            27.00   
15           605.03               32.933856            27.20   
17          1303.01               41.702573            17.10   
21          1303.01               39.783993            18.20   
22          1303.01               38.068624            18.30   
23          1303.01               38.374753            18.40   
24           632.46               26.544229            17.30   

   PaymentofMinAmount  Amountinvestedmonthly              PaymentBehaviour  \
6                  No             178.344067    LowspentSmallvaluepayments   
9                  No              40.391238   HighspentLargevaluepayments   
12                 No             130.115420    LowspentSmallvaluepayments   
13                 No              43.477190   HighspentLargevaluepayments   
15                 No             218.904344    LowspentSmallvaluepayments   
17                 No             232.860384   HighspentSmallvaluepayments   
21                 No             257.808099  HighspentMediumvaluepayments   
22                 No             263.174163   HighspentSmallvaluepayments   
23                 No           10000.000000   HighspentSmallvaluepayments   
24                 No              81.228859    LowspentLargevaluepayments   

    MonthlyBalance CreditScore  
6     

In [502]:
def convert_to_numeric_or_nan(value):
    try:
        return float(value)
    except ValueError:
        if value == '__-333333333333333333333333333__':
            return np.nan
        else:
            return value

# Apply the custom function to convert numeric values and handle the specific non-numeric value
for column in df.columns:
    df[column] = df[column].apply(convert_to_numeric_or_nan)

In [503]:
columns_to_convert = ['Occupation',
 'CreditMix',
 'PaymentofMinAmount',
 'PaymentBehaviour',
 'CreditScore']

encoder = LabelEncoder()

for i in columns_to_convert:
    data[i] = encoder.fit_transform(data[i])

In [504]:
data.dtypes

Age                         int64
Occupation                  int32
AnnualIncome              float64
MonthlyInhandSalary       float64
NumBankAccounts             int64
NumCreditCard               int64
InterestRate                int64
NumofLoan                   int64
Delayfromduedate            int64
NumofDelayedPayment       float64
ChangedCreditLimit        float64
NumCreditInquiries        float64
CreditMix                   int32
OutstandingDebt           float64
CreditUtilizationRatio    float64
CreditHitoryAge           float64
PaymentofMinAmount          int32
Amountinvestedmonthly     float64
PaymentBehaviour            int32
MonthlyBalance            float64
CreditScore                 int32
dtype: object

In [505]:
data.head()

Age  Occupation  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
6    23          12      19114.12          1824.843333                2   
9    28          13      34847.84          3037.986667                1   
12   28          13      34847.84          3037.986667                1   
13   28          13      34847.84          3037.986667                2   
15   28          13      34847.84          3037.986667                2   

    NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
6               1             3          4                 3   
9               1             6          1                 7   
12              1             6          1                 3   
13              1             6          1                 3   
15              1             6          1                 3   

    NumofDelayedPayment  ChangedCreditLimit  NumCreditInquiries  CreditMix  \
6                   8.0               11.27                 4.0          1   
9                   1.0                7.42                 2.0          1   
12                  1.0                6.42                 2.0          1   
13                  0.0                5.42                 2.0          1   
15                  4.0                5.42                 2.0          1   

    OutstandingDebt  CreditUtilizationRatio  CreditHitoryAge  \
6            809.98               22.537593            22.70   
9            605.03               38.550848            26.80   
12           605.03               34.977895            26.11   
13           605.03               33.381010            27.00   
15           605.03               32.933856            27.20   

    PaymentofMinAmount  Amountinvestedmonthly  PaymentBehaviour  \
6                    0             178.344067                 5   
9                    0              40.391238                 0   
12                   0             130.115420                 5   
13                   0              43.477190                 0   
15                   0             218.904344                 5   

    MonthlyBalance  CreditScore  
6       244.565317            0  
9       484.591214            0  
12      444.867032            0  
13      481.505262            0  
15      356.078109            0

In [506]:
data.shape

(39362, 21)

In [507]:
data.dtypes

Age                         int64
Occupation                  int32
AnnualIncome              float64
MonthlyInhandSalary       float64
NumBankAccounts             int64
NumCreditCard               int64
InterestRate                int64
NumofLoan                   int64
Delayfromduedate            int64
NumofDelayedPayment       float64
ChangedCreditLimit        float64
NumCreditInquiries        float64
CreditMix                   int32
OutstandingDebt           float64
CreditUtilizationRatio    float64
CreditHitoryAge           float64
PaymentofMinAmount          int32
Amountinvestedmonthly     float64
PaymentBehaviour            int32
MonthlyBalance            float64
CreditScore                 int32
dtype: object

In [508]:
X = data.drop(columns='CreditScore')
y = data['CreditScore']

In [509]:
X.shape

(39362, 20)

In [510]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
X = minmax.fit_transform(X)


In [511]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [512]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0, max_iter= 2000)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=2000, random_state=0)

In [513]:
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [518]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print(f"\n accuracy: {round(accuracy_score(y_test, y_pred)*100,2)}%")

[[1073   29  989]
 [ 213 1479 1708]
 [ 724  878 4716]]

 accuracy: 61.55%


In [519]:
data.sample(1)

Age  Occupation  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
23377   40           5      63461.28              5109.44                8   

       NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
23377              7             6          4                 6   

       NumofDelayedPayment  ChangedCreditLimit  NumCreditInquiries  CreditMix  \
23377                 15.0               12.39                 5.0          2   

       OutstandingDebt  CreditUtilizationRatio  CreditHitoryAge  \
23377          1266.31               25.907566             11.5   

       PaymentofMinAmount  Amountinvestedmonthly  PaymentBehaviour  \
23377                   1                 70.251                 1   

       MonthlyBalance  CreditScore  
23377      514.056034            2